import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
//import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Reset Pasword</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="flex h-screen justify-center items-center w-full flex-1 px-48 gap-10 bg-white">
        <div
          className="w-full h-5/6 rounded-3xl shadow-lg p-10 m-1 bg-cover"
          style={{ backgroundImage: 'url("/background.png")' }}
        >
          <div className="w-72 max-w-md mx-auto my-10 bg-white p-5 rounded-3xl shadow-md">
            <h3 className="text-center text-3xl mb-4">
              Reset <br />
              Password
            </h3>
            <form>
              <div className="mb-4">
                <label
                  className="block text-gray-700 mb-2"
                  htmlFor="new_password"
                >
                  New Password
                </label>
                <input
                  className="shadow appearance-none border rounded-xl w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  id="new_password"
                  type="password"
                  placeholder="Password"
                />
              </div>
              <div className="mb-4">
                <label
                  className="block text-gray-700 mb-2"
                  htmlFor="confirm_password"
                >
                  Confirm Password
                </label>
                <input
                  className="shadow appearance-none border rounded-xl w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  id="confirm_password"
                  type="password"
                  placeholder="Password"
                />
              </div>
              <div className="mb-4">
                <button
                  className=" w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline justify-center"
                  type="button"
                >
                  Confirm
                </button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
